import React, { createContext, useContext, useState, useEffect } from 'react';
import { subsidiesHi, subsidiesTe } from './subsidiesTranslations';

const LanguageContext = createContext();

const translations = {
  en: {
    // Navbar & Layout
    home: "Home",
    services: "Services",
    pricing: "Mandi Prices",
    weather: "Weather",
    testing: "Soil Testing",
    schemes: "Schemes & Subsidies",
    donate: "Donate",
    contact: "Contact Us",
    about: "About Us",
    login: "Login",
    signup: "Sign Up",
    logout: "Logout",
    profile: "Manage Profile",
    theme: "Change Theme",
    adminPanel: "Admin Panel",
    welcome: "Welcome back to AgroMitra",
    recentServices: "Recently Used Services",
    supportTitle: "Need Assistance?",
    supportDesc: "Our agricultural experts are available 24/7 to help you with any questions or issues you may have regarding our services.",
    callNow: "Call Now",
    emailNow: "Email Now",
    location: "Select Location",
    
    // Help Center / FAQ
    faqTitle: "AgroMitra Help Center",
    faqSubtitle: "Find answers to common questions or ask our AI assistant anything about our services.",
    aiSearchTitle: "Ask AgroMitra AI Assistant",
    aiSearchPlaceholder: "Type your question here (e.g. 'Who built this?' or 'How does soil testing work?')...",
    searching: "Searching...",
    search: "Ask",
    matchedQuestion: "Matched Question",
    aiResponse: "AI Response",
    generalFaqTitle: "Frequently Asked Questions",
    
    // Contact Us
    contactUsTitle: "Contact Us / Support",
    contactUsSubtitle: "Have questions or feedback? Send us a query and our experts will reply promptly.",
    nameLabel: "Name",
    contactNamePlaceholder: "Enter your name",
    emailLabel: "Email Address",
    contactEmailPlaceholder: "Enter your email",
    subjectLabel: "Subject",
    subjectPlaceholder: "What is this regarding?",
    messageLabel: "Your Message / Inquiry",
    messagePlaceholder: "Describe your inquiry in detail...",
    sending: "Submitting...",
    submitQuery: "Submit Inquiry",
    querySuccess: "Your message has been submitted successfully! Our team will get back to you shortly.",
    
    // Weather Predictor
    weatherTitle: "Weather Predictor",
    weatherSubtitle: "Enter daily weather metrics or trigger the Weekly Observatory to examine week-long crop advice.",
    sensorAutofill: "Sensor Autofill",
    weeklyObservatory: "Weekly Observatory",
    precipitationLabel: "Precipitation (mm)",
    maxTempLabel: "Max Temp (°C)",
    minTempLabel: "Min Temp (°C)",
    windLabel: "Wind Speed (km/h)",
    predictButtonSingle: "Predict Single-Day Weather",
    adviceHeading: "Smart Agricultural Advice:",
    predictionHeading: "Predicted Condition",
    observatoryTitle: "Weekly Weather Observatory",
    stationLabel: "Detected Station",
    forecastLabel: "7-Day Forecast",
    advisoryFor: "Advisory for",
    
    // Fertilizer Advisor
    soilAdvisorTitle: "Fertilizer Advisory Tool",
    soilAdvisorSubtitle: "Input soil NPK and pH values to get optimal fertilizer suggestions.",
    nitrogenLabel: "Nitrogen (N)",
    phosphorusLabel: "Phosphorus (P)",
    potassiumLabel: "Potassium (K)",
    temperatureLabel: "Temp (°C)",
    humidityLabel: "Humidity (%)",
    moistureLabel: "Moisture (%)",
    soilTypeLabel: "Soil Type",
    cropTypeLabel: "Crop Type",
    importSoilReport: "Import Soil Report",
    generateRecommendation: "Generate Advisor Recommendation",
    calculating: "Calculating...",
    soilTestSummary: "Soil Test Summary / Remarks",
    
    // Mandi Prices
    mandiTitle: "Mandi Price Index",
    mandiSubtitle: "Real-time agricultural commodity prices from government databases",
    searchState: "Search State",
    searchCommodity: "Search Commodity",
    filterDistrict: "Filter District/Market",
    refreshBtn: "Refresh Live Data",
    mandiTableCrop: "Crop",
    mandiTableVariety: "Variety",
    mandiTableMarket: "Market / State",
    mandiTableMin: "Min Price",
    mandiTableMax: "Max Price",
    mandiTableModal: "Modal Price",
    mandiTableDate: "Date",
    
    // Subsidies & Schemes
    subsidiesTitle: "Subsidies & Schemes Matcher",
    subsidiesSubtitle: "Find and match government schemes for farmers and crop support.",
    filterEligibility: "Filter Eligibility",
    matcherFormState: "State",
    matcherFormCrop: "Primary Crop",
    matcherFormLand: "Land Size (Acres)",
    matcherFormIncome: "Annual Income (INR)",
    matcherCheckBtn: "Check My Eligibility",
    matchedSchemes: "Matched Schemes",
    aiChatSubtitle: "Schemes Assistant Chatbot",
    
    // Deals Shop
    shopTitle: "AgroMitra Shop",
    shopSubtitle: "Purchase agricultural seeds and equipment",
    shoppingCart: "Shopping Cart",
    emptyCart: "Your cart is empty. Add some products!",
    totalAmount: "Total Amount",
    shippingDetails: "Shipping Details",
    shippingName: "Recipient Name",
    shippingAddress: "Shipping Address",
    shippingPhone: "Contact Number",
    placeOrder: "Place Order & Pay",
    addToCart: "Add to Cart",
    
    // About Us
    aboutMission: "Our Mission",
    aboutMissionDesc: "To empower farmers through AI-driven insights, live mandi prices, and smart agricultural advisors to create a sustainable and prosperous farming future.",
    aboutStory: "Our Story",
    aboutStoryDesc: "AgroMitra was built to bridge the gap between technology and the roots of agriculture. By providing real-time data on weather, soil health, and market trends, we enable farmers to make data-driven decisions.",
    aboutDesc: "AgroMitra is a state-of-the-art agricultural advisory platform built to empower local Indian farmers. By leveraging machine learning, we provide real-time recommendations for soil fertilizing, crop price alerts (Mandi), weather prediction advisories, and matched government subsidies.",
    aboutTeam: "VIT-AP Development Team",
    aboutTeamDesc: "Developed as a Capstone Initiative at VIT-AP University.",
    projectLeads: "Project Leads",
    emailLabelShort: "Email",
    locationLabelShort: "Location",

    // Footer
    quickLinks: "Quick Links",
    ourOffice: "Our Office",
    connectWithUs: "Connect With Us",
    cultivatingFuture: "Cultivating the future of sustainable farming",
    copyright: "© 2025 AgroMitra. Licensed under MIT License.",

    // Login / Signup / Verify
    loginHeader: "Login",
    signupHeader: "Sign Up",
    emailPlaceholder: "Email",
    passwordPlaceholder: "Password",
    loginWithGoogle: "Login with Google",
    signupWithGoogle: "Sign up with Google",
    noAccount: "Don't have an account?",
    alreadyAccount: "Already have an account?",
    namePlaceholder: "Name",
    phonePlaceholder: "Phone Number",
    selectRole: "Select Role",
    roleFarmer: "Farmer",
    roleCustomer: "Customer",
    requestOtp: "Request OTP",
    sendingOtp: "Sending OTP...",
    verifyOtpHeader: "Verify OTP",
    verifyOtpPrompt: "Please enter the OTP sent to",
    enterOtpPlaceholder: "Enter OTP",
    verifying: "Verifying...",

    // Dashboard
    adminConsoleSim: "🛠️ Admin Console Simulator",
    viewMode: "View Mode:",
    farmerDashboard: "Farmer Dashboard",
    customerDashboard: "Customer Dashboard",
    backToAdmin: "← Back to Admin Console",

    // ServiceSection
    loadingActivities: "Loading activities...",
    noRecentActivityCustomer: "No recent activity. Try checking our weather predictions or deals shop!",
    noRecentActivityFarmer: "No recent activity. Try checking our weather predictions or fertilizer advisories below!",
    viewAllServices: "View All Services",
    customerCare: "Customer Care",
    emailSupport: "Email Support",
    serviceHistoryLogs: "Service History Logs",
    closeModal: "Close modal",
    noActivitiesFound: "No activities found.",
    openBtn: "Open",
    continueBtn: "Continue",
    forecastBtn: "Forecast",
    advisoryBtn: "Advisory",
    matcherBtn: "Matcher",
    trackBtn: "Track",
    viewBtn: "View",
    weatherPrediction: "Weather Prediction",
    fertilizerRecommendation: "Fertilizer Recommendation",
    subsidiesMatcher: "Subsidies Matcher",
    soilTestingRequest: "Soil Testing Request",
    marketplaceListing: "Marketplace Listing",
    productPurchase: "Product Purchase",

    // RecommendedFeatures
    recommendedFeaturesTitle: "Recommended Features",
    reports: "Reports",
    reportsDesc: "Access various agricultural diagnostics and recommendations",
    weatherReportTitle: "Weather Report",
    weatherReportDesc: "Get weather predictions and crop advisory tips.",
    soilReportTitle: "Soil Report",
    soilReportDesc: "Request physical soil tests and check report history.",
    priceReportTitle: "Price Report",
    priceReportDesc: "Current market prices for agricultural produce.",
    fertilizerReportTitle: "Fertilizer Report",
    fertilizerReportDesc: "Optimal fertilizer recommendations based on soil NPK.",
    accessTool: "Access Tool",
    cropListingsTitle: "Crop Listings",
    postMyCrop: "+ Post My Crop",
    cropListingsDesc: "Sell seeds or crops directly to other farmers and merchants",
    loadingCropListings: "Loading crop listings...",
    listingsCount: "listings",
    viewPostings: "View Postings",
    postCropModalTitle: "Post New Crop / Seed Listing",
    selectCrop: "Select Crop",
    cropCategory: "Crop Category",
    vegetables: "Vegetables",
    cereals: "Cereals",
    pulses: "Pulses",
    spices: "Spices",
    quantityQuintals: "Quantity (Quantity in Quintals)",
    pricePerQuintal: "Price per Quintal (₹)",
    yourFullName: "Your Full Name",
    yourPhoneNumber: "Your Phone Number",
    postListing: "Post Listing",
    posting: "Posting...",
    close: "Close",
    cropPostingsFor: "Crop Postings for",
    noPostingsInCategory: "No listings found in this category yet.",
    farmerLabel: "Farmer",
    phoneLabel: "Phone",
    priceLabel: "Price",
    qtyLabel: "Quantity",

    // Soil Testing
    requestSoilTestTitle: "Request Soil Test",
    requestSoilTestDesc: "Schedule a physical soil sample collection from your farm. Our experts will test and upload your soil health report.",
    farmLocationAddress: "Farm Location / Address",
    farmAddressPlaceholder: "Enter full farm address for sample pickup",
    preferredCollectionDate: "Preferred Collection Date",
    schedulePickup: "Schedule Pickup",
    yourSoilReports: "Your Soil Reports & Requests",
    noSoilRequests: "No soil test requests scheduled yet.",
    pickupAddress: "Pickup Address",
    scheduledCollection: "Scheduled Collection",
    getAdvisorRec: "Get Advisor Rec",
    statusCompleted: "Completed",
    statusAnalyzing: "Analyzing",
    statusCollected: "Collected",
    statusPending: "Pending",

    // My Orders
    backToShop: "Back to Shop",
    myOrdersTitle: "My Orders",
    loadingOrders: "Loading your orders...",
    noOrdersPlaced: "No Orders Placed Yet",
    exploreShopDesc: "Explore the deals shop to purchase high-yield seeds, fertilizers, and high-quality farming equipment.",
    shopNow: "Shop Now",
    orderPlaced: "ORDER PLACED",
    total: "TOTAL",
    orderId: "ORDER ID",
    itemsOrdered: "Items Ordered",
    recipientPhone: "Phone",
    recipientAddress: "Address",
    noShippingDetails: "No shipping details provided.",
    statusProcessing: "Processing",
    statusShipped: "Shipped",
    statusDelivered: "Delivered",
    statusCancelled: "Cancelled",

    // Subsidies / Chatbot
    allCentral: "All / Central",
    allCrops: "All Crops",
    categoryAll: "All",
    categoryAgri: "Agriculture",
    categoryFinance: "Finance",
    categoryTech: "Technology",
    eligible: "Eligible",
    ineligible: "Ineligible",
    matches: "Matches",
    benefitValue: "Benefit Value",
    noSchemesMatch: "No schemes match your parameters.",
    advisoryBotTitle: "Advisory Scheme Bot",
    advisoryBotSubtitle: "Agricultural Scheme Assistant",
    botWelcome: 'Namaste! I am your AgroMitra Subsidy Assistant. Ask me anything about government schemes, loans, crop insurance, or solar pump subsidies (e.g. "How to register for PM Kisan?").',
    botError: "Sorry, I am facing trouble connecting to the advisory server. Please try again.",
    botNetworkError: "Network connection issue.",
    botPlaceholder: "Type your subsidy question here...",

    // Donate
    supportTitleDonate: "Support AgroMitra",
    supportDescDonate: "Your contributions help us maintain soil testing centers, update agricultural ML models, and distribute smart kits to small farmers.",
    customAmount: "Custom",
    enterAmountPlaceholder: "Enter amount (₹)",
    contributeNow: "Contribute Now",
    processing: "Processing...",
    invalidAmount: "Please enter a valid amount.",
    failedCreateOrder: "Failed to create order",
    offlineError: "Razorpay SDK failed to load. Are you offline?",
    verifyFailed: "Payment mock verification failed",
    mockSuccess: "Success! Thank you for supporting AgroMitra! (Transaction Mocked)",
    successContribute: "Thank you for your generous contribution! Your payment was successful.",
    sigFailed: "Signature verification failed",
    errCheckout: "Error initiating checkout."
  },
  hi: {
    // Navbar & Layout
    home: "मुख्य पृष्ठ",
    services: "सेवाएं",
    pricing: "मंडी दरें",
    weather: "मौसम",
    testing: "मिट्टी परीक्षण",
    schemes: "योजनाएं और सब्सिडी",
    donate: "दान करें",
    contact: "संपर्क करें",
    about: "हमारे बारे में",
    login: "लॉगिन",
    signup: "साइन अप",
    logout: "लॉगआउट",
    profile: "प्रोफ़ाइल प्रबंधित करें",
    theme: "थीम बदलें",
    adminPanel: "एडमिन पैनल",
    welcome: "एग्रोमित्रा में स्वागत है",
    recentServices: "हाल ही में उपयोग की गई सेवाएं",
    supportTitle: "मदद की ज़रूरत है?",
    supportDesc: "हमारे कृषि विशेषज्ञ हमारी सेवाओं के संबंध में आपके किसी भी प्रश्न या समस्या में मदद करने के लिए 24/7 उपलब्ध हैं।",
    callNow: "अभी कॉल करें",
    emailNow: "अभी ईमेल करें",
    location: "स्थान चुनें",
    
    // Help Center / FAQ
    faqTitle: "एग्रोमित्रा सहायता केंद्र",
    faqSubtitle: "सामान्य प्रश्नों के उत्तर खोजें या हमारी सेवाओं के बारे में हमारे एआई सहायक से कुछ भी पूछें।",
    aiSearchTitle: "एग्रोमित्रा एआई सहायक से पूछें",
    aiSearchPlaceholder: "अपना प्रश्न यहाँ टाइप करें (जैसे 'यह किसने बनाया?' या 'मिट्टी परीक्षण कैसे काम करता है?')...",
    searching: "खोज रहा है...",
    search: "पूछें",
    matchedQuestion: "मिलता-जुलता प्रश्न",
    aiResponse: "एआई प्रतिक्रिया",
    generalFaqTitle: "अक्सर पूछे जाने वाले प्रश्न",
    
    // Contact Us
    contactUsTitle: "हमसे संपर्क करें / सहायता",
    contactUsSubtitle: "कोई प्रश्न या प्रतिक्रिया है? हमें संदेश भेजें और हमारे विशेषज्ञ जल्द ही जवाब देंगे।",
    nameLabel: "नाम",
    contactNamePlaceholder: "अपना नाम दर्ज करें",
    emailLabel: "ईमेल पता",
    contactEmailPlaceholder: "अपना ईमेल दर्ज करें",
    subjectLabel: "विषय",
    subjectPlaceholder: "यह किस संबंध में है?",
    messageLabel: "आपका संदेश / पूछताछ",
    messagePlaceholder: "अपनी पूछताछ का विस्तार से वर्णन करें...",
    sending: "जमा किया जा रहा है...",
    submitQuery: "पूछताछ भेजें",
    querySuccess: "आपका संदेश सफलतापूर्वक भेज दिया गया है! हमारी टीम जल्द ही आपसे संपर्क करेगी।",
    
    // Weather Predictor
    weatherTitle: "मौसम भविष्यवक्ता",
    weatherSubtitle: "दैनिक मौसम मीट्रिक दर्ज करें या सप्ताह भर की फसल सलाह की जांच करने के लिए साप्ताहिक वेधशाला को सक्रिय करें।",
    sensorAutofill: "सेंसर ऑटोफिल",
    weeklyObservatory: "साप्ताहिक वेधशाला",
    precipitationLabel: "वर्षा (मिमी)",
    maxTempLabel: "अधिकतम तापमान (°C)",
    minTempLabel: "न्यूनतम तापमान (°C)",
    windLabel: "हवा की गति (किमी/घंटा)",
    predictButtonSingle: "एकल-दिवस मौसम की भविष्यवाणी करें",
    adviceHeading: "स्मार्ट कृषि सलाह:",
    predictionHeading: "अनुमानित स्थिति",
    observatoryTitle: "साप्ताहिक मौसम वेधशाला",
    stationLabel: "खोजा गया स्टेशन",
    forecastLabel: "7-दिवसीय पूर्वानुमान",
    advisoryFor: "के लिए सलाह",
    
    // Fertilizer Advisor
    soilAdvisorTitle: "उर्वरक सलाहकार उपकरण",
    soilAdvisorSubtitle: "इष्टतम उर्वरक सुझाव प्राप्त करने के लिए मिट्टी के एनपीके और पीएच मान दर्ज करें।",
    nitrogenLabel: "नाइट्रोजन (N)",
    phosphorusLabel: "फास्फोरस (P)",
    potassiumLabel: "पोटेशियम (K)",
    temperatureLabel: "तापमान (°C)",
    humidityLabel: "आर्द्रता (%)",
    moistureLabel: "नमी (%)",
    soilTypeLabel: "मिट्टी का प्रकार",
    cropTypeLabel: "फसल का प्रकार",
    importSoilReport: "मिट्टी की रिपोर्ट आयात करें",
    generateRecommendation: "सलाहकार सिफारिश उत्पन्न करें",
    calculating: "गणना की जा रही है...",
    soilTestSummary: "मिट्टी परीक्षण सारांश / टिप्पणियाँ",
    
    // Mandi Prices
    mandiTitle: "मंडी दर सूचकांक",
    mandiSubtitle: "सरकारी डेटाबेस से वास्तविक समय की कृषि वस्तु दरें",
    searchState: "राज्य खोजें",
    searchCommodity: "फसल खोजें",
    filterDistrict: "जिला / बाजार फ़िल्टर करें",
    refreshBtn: "लाइव डेटा रीफ्रेश करें",
    mandiTableCrop: "फसल",
    mandiTableVariety: "किस्म",
    mandiTableMarket: "बाजार / राज्य",
    mandiTableMin: "न्यूनतम दर",
    mandiTableMax: "अधिकतम दर",
    mandiTableModal: "औसत दर",
    mandiTableDate: "तारीख",
    
    // Subsidies & Schemes
    subsidiesTitle: "सब्सिडी और योजनाएं मिलानकर्ता",
    subsidiesSubtitle: "किसानों और फसल सहायता के लिए सरकारी योजनाओं को ढूंढें और मिलान करें।",
    filterEligibility: "पात्रता फ़िल्टर करें",
    matcherFormState: "राज्य",
    matcherFormCrop: "मुख्य फसल",
    matcherFormLand: "भूमि का आकार (एकड़)",
    matcherFormIncome: "वार्षिक आय (INR)",
    matcherCheckBtn: "मेरी पात्रता जांचें",
    matchedSchemes: "योग्य योजनाएं",
    aiChatSubtitle: "योजना सहायक चैटबॉट",
    
    // Deals Shop
    shopTitle: "एग्रोमित्रा शॉप",
    shopSubtitle: "कृषि बीज और उपकरण खरीदें",
    shoppingCart: "शॉपिंग कार्ट",
    emptyCart: "आपका कार्ट खाली है। कुछ उत्पाद जोड़ें!",
    totalAmount: "कुल राशि",
    shippingDetails: "शिपिंग विवरण",
    shippingName: "प्राप्तकर्ता का नाम",
    shippingAddress: "शिपिंग पता",
    shippingPhone: "संपर्क नंबर",
    placeOrder: "ऑर्डर दें और भुगतान करें",
    addToCart: "कार्ट में जोड़ें",
    
    // About Us
    aboutMission: "हमारा उद्देश्य",
    aboutMissionDesc: "कृषि क्षेत्र को समृद्ध और संधारणीय बनाने के लिए किसानों को एआई-संचालित विश्लेषण, लाइव मंडी दरों और स्मार्ट सलाहकार उपकरणों से सशक्त बनाना।",
    aboutStory: "हमारी कहानी",
    aboutStoryDesc: "तकनीक और खेती की जड़ों के बीच के अंतर को कम करने के लिए एग्रोमित्रा का निर्माण किया गया था। मौसम, मिट्टी के स्वास्थ्य और बाजार के रुझान की लाइव जानकारी देकर, हम किसानों को सही निर्णय लेने में मदद करते हैं।",
    aboutDesc: "एग्रोमित्रा एक अत्याधुनिक कृषि सलाहकार मंच है जिसे स्थानीय भारतीय किसानों को सशक्त बनाने के लिए बनाया गया है। मशीन लर्निंग का लाभ उठाकर, हम मिट्टी के उर्वरीकरण, फसल मूल्य अलर्ट (मंडी), मौसम पूर्वानुमान सलाह और संबंधित सरकारी सब्सिडी के लिए वास्तविक समय की सिफारिशें प्रदान करते हैं।",
    aboutTeam: "VIT-AP विकास टीम",
    aboutTeamDesc: "VIT-AP विश्वविद्यालय में एक कैपस्टोन पहल के रूप में विकसित।",
    projectLeads: "परियोजना प्रमुख",
    emailLabelShort: "ईमेल",
    locationLabelShort: "स्थान",

    // Footer
    quickLinks: "त्वरित लिंक",
    ourOffice: "हमारा कार्यालय",
    connectWithUs: "हमसे जुड़ें",
    cultivatingFuture: "टिकाऊ खेती के भविष्य को संवारना",
    copyright: "© 2025 एग्रोमित्रा। एमआईटी लाइसेंस के तहत लाइसेंस प्राप्त।",

    // Login / Signup / Verify
    loginHeader: "लॉगिन",
    signupHeader: "साइन अप",
    emailPlaceholder: "ईमेल",
    passwordPlaceholder: "पासवर्ड",
    loginWithGoogle: "गूगल के साथ लॉगिन करें",
    signupWithGoogle: "गूगल के साथ साइन अप करें",
    noAccount: "खाता नहीं है?",
    alreadyAccount: "पहले से ही एक खाता है?",
    namePlaceholder: "नाम",
    phonePlaceholder: "फ़ोन नंबर",
    selectRole: "भूमिका चुनें",
    roleFarmer: "किसान",
    roleCustomer: "ग्राहक",
    requestOtp: "ओटीपी अनुरोध करें",
    sendingOtp: "ओटीपी भेजा जा रहा है...",
    verifyOtpHeader: "ओटीपी सत्यापित करें",
    verifyOtpPrompt: "कृपया नीचे भेजे गए ओटीपी को दर्ज करें",
    enterOtpPlaceholder: "ओटीपी दर्ज करें",
    verifying: "सत्यापित किया जा रहा है...",

    // Dashboard
    adminConsoleSim: "🛠️ एडमिन कंसोल सिम्युलेटर",
    viewMode: "दृश्य मोड:",
    farmerDashboard: "किसान डैशबोर्ड",
    customerDashboard: "ग्राहक डैशबोर्ड",
    backToAdmin: "← एडमिन कंसोल पर वापस जाएं",

    // ServiceSection
    loadingActivities: "गतिविधियाँ लोड हो रही हैं...",
    noRecentActivityCustomer: "कोई हालिया गतिविधि नहीं। हमारे मौसम पूर्वानुमान या डील्स शॉप को देखने का प्रयास करें!",
    noRecentActivityFarmer: "कोई हालिया गतिविधि नहीं। नीचे हमारे मौसम पूर्वानुमान या उर्वरक सलाह को देखने का प्रयास करें!",
    viewAllServices: "सभी सेवाएं देखें",
    customerCare: "कस्टमर केयर",
    emailSupport: "ईमेल सहायता",
    serviceHistoryLogs: "सेवा इतिहास लॉग",
    closeModal: "बंद करें",
    noActivitiesFound: "कोई गतिविधि नहीं मिली।",
    openBtn: "खोलें",
    continueBtn: "जारी रखें",
    forecastBtn: "पूर्वानुमान",
    advisoryBtn: "सलाहकार",
    matcherBtn: "मिलानकर्ता",
    trackBtn: "ट्रैक करें",
    viewBtn: "देखें",
    weatherPrediction: "मौसम का पूर्वानुमान",
    fertilizerRecommendation: "उर्वरक की सिफारिश",
    subsidiesMatcher: "सब्सिडी मिलानकर्ता",
    soilTestingRequest: "मिट्टी परीक्षण अनुरोध",
    marketplaceListing: "मार्केटप्लेस लिस्टिंग",
    productPurchase: "उत्पाद खरीद",

    // RecommendedFeatures
    recommendedFeaturesTitle: "अनुशंसित विशेषताएं",
    reports: "रिपोर्टें",
    reportsDesc: "विभिन्न कृषि निदान और सिफारिशों तक पहुंचें",
    weatherReportTitle: "मौसम रिपोर्ट",
    weatherReportDesc: "मौसम का पूर्वानुमान और फसल संबंधी सलाह प्राप्त करें।",
    soilReportTitle: "मिट्टी रिपोर्ट",
    soilReportDesc: "मिट्टी के भौतिक परीक्षण का अनुरोध करें और रिपोर्ट का इतिहास देखें।",
    priceReportTitle: "मूल्य रिपोर्ट",
    priceReportDesc: "कृषि उपज के लिए वर्तमान बाजार दरें।",
    fertilizerReportTitle: "उर्वरक रिपोर्ट",
    fertilizerReportDesc: "मिट्टी एनपीके के आधार पर इष्टतम उर्वरक सिफारिशें।",
    accessTool: "उपकरण खोलें",
    cropListingsTitle: "फसल लिस्टिंग",
    postMyCrop: "+ मेरी फसल पोस्ट करें",
    cropListingsDesc: "बीज या फसल सीधे अन्य किसानों और व्यापारियों को बेचें",
    loadingCropListings: "फसल सूची लोड हो रही है...",
    listingsCount: "लिस्टिंग",
    viewPostings: "पोस्टिंग देखें",
    postCropModalTitle: "नई फसल / बीज लिस्टिंग पोस्ट करें",
    selectCrop: "फसल चुनें",
    cropCategory: "फसल श्रेणी",
    vegetables: "सब्जियां",
    cereals: "अनाज",
    pulses: "दालें",
    spices: "मसाले",
    quantityQuintals: "मात्रा (क्विंटल में)",
    pricePerQuintal: "प्रति क्विंटल मूल्य (₹)",
    yourFullName: "आपका पूरा नाम",
    yourPhoneNumber: "आपका फ़ोन नंबर",
    postListing: "लिस्टिंग पोस्ट करें",
    posting: "पोस्ट किया जा रहा है...",
    close: "बंद करें",
    cropPostingsFor: "फसल पोस्टिंग के लिए",
    noPostingsInCategory: "इस श्रेणी में अभी तक कोई लिस्टिंग नहीं मिली।",
    farmerLabel: "किसान",
    phoneLabel: "फ़ोन",
    priceLabel: "मूल्य",
    qtyLabel: "मात्रा",

    // Soil Testing
    requestSoilTestTitle: "मिट्टी परीक्षण का अनुरोध करें",
    requestSoilTestDesc: "अपने खेत से भौतिक मिट्टी के नमूने के संग्रह का समय निर्धारित करें। हमारे विशेषज्ञ परीक्षण करेंगे और आपकी मिट्टी की रिपोर्ट अपलोड करेंगे।",
    farmLocationAddress: "खेत का स्थान / पता",
    farmAddressPlaceholder: "नमूना पिकअप के लिए खेत का पूरा पता दर्ज करें",
    preferredCollectionDate: "पसंदीदा संग्रह तिथि",
    schedulePickup: "पिकअप शेड्यूल करें",
    yourSoilReports: "आपकी मिट्टी की रिपोर्ट और अनुरोध",
    noSoilRequests: "अभी तक कोई मिट्टी परीक्षण अनुरोध निर्धारित नहीं किया गया है।",
    pickupAddress: "पिकअप का पता",
    scheduledCollection: "निर्धारित संग्रह",
    getAdvisorRec: "सलाहकार सिफारिश प्राप्त करें",
    statusCompleted: "पूरा हुआ",
    statusAnalyzing: "विश्लेषण किया जा रहा है",
    statusCollected: "एकत्रित किया गया",
    statusPending: "लंबित",

    // My Orders
    backToShop: "दुकान पर वापस जाएं",
    myOrdersTitle: "मेरे ऑर्डर्स",
    loadingOrders: "आपके ऑर्डर लोड हो रहे हैं...",
    noOrdersPlaced: "अभी तक कोई ऑर्डर नहीं दिया गया",
    exploreShopDesc: "उच्च उपज वाले बीज, उर्वरक और उच्च गुणवत्ता वाले कृषि उपकरण खरीदने के लिए डील्स शॉप देखें।",
    shopNow: "अभी खरीदें",
    orderPlaced: "ऑर्डर दिया गया",
    total: "कुल",
    orderId: "ऑर्डर आईडी",
    itemsOrdered: "ऑर्डर की गई वस्तुएं",
    recipientPhone: "फ़ोन",
    recipientAddress: "पता",
    noShippingDetails: "कोई शिपिंग विवरण प्रदान नहीं किया गया।",
    statusProcessing: "प्रसंस्करण",
    statusShipped: "भेज दिया गया",
    statusDelivered: "वितरित",
    statusCancelled: "रद्द किया गया",

    // Subsidies / Chatbot
    allCentral: "सभी / केंद्रीय",
    allCrops: "सभी फसलें",
    categoryAll: "सभी",
    categoryAgri: "कृषि",
    categoryFinance: "वित्त",
    categoryTech: "प्रौद्योगिकी",
    eligible: "पात्र",
    ineligible: "अपात्र",
    matches: "मेल खाता है",
    benefitValue: "लाभ मूल्य",
    noSchemesMatch: "आपके मापदंडों से मेल खाने वाली कोई योजना नहीं है।",
    advisoryBotTitle: "सलाहकार योजना बॉट",
    advisoryBotSubtitle: "कृषि योजना सहायक",
    botWelcome: 'नमस्ते! मैं आपका एग्रोमित्रा सब्सिडी सहायक हूं। मुझसे सरकारी योजनाओं, ऋण, फसल बीमा, या सौर पंप सब्सिडी के बारे में कुछ भी पूछें (जैसे "पीएम किसान के लिए पंजीकरण कैसे करें?")।',
    botError: "क्षमा करें, मुझे सलाहकार सर्वर से कनेक्ट करने में परेशानी हो रही है। कृपया पुनः प्रयास करें।",
    botNetworkError: "नेटवर्क कनेक्शन की समस्या।",
    botPlaceholder: "अपनी सब्सिडी संबंधी प्रश्न यहां टाइप करें...",

    // Dynamic Categories
    "Agriculture": "कृषि",
    "Finance": "वित्त",
    "Technology": "प्रौद्योगिकी",
    "Irrigation": "सिंचाई",

    // Dynamic Scheme Translations
    "PM-Kisan": "पीएम-किसान",
    "Direct income support of Rs 6000 per year paid in three equal installments of Rs 2000 to all small landholding families.": "सभी छोटे भूमिधारक परिवारों को प्रति वर्ष ₹6000 की प्रत्यक्ष आय सहायता, ₹2000 की तीन समान किश्तों में दी जाएगी।",
    "PM Fasal Bima Yojana": "पीएम फसल बीमा योजना",
    "Crop insurance with low premium (1.5% to 5%) covering yield loss due to droughts floods pests and localized calamities.": "कम प्रीमियम (1.5% से 5%) के साथ फसल बीमा, जो सूखे, बाढ़, कीटों और स्थानीय आपदाओं के कारण होने वाले नुकसान को कवर करता है।",
    "Per Drop More Crop (PMKSY)": "प्रति बूंद अधिक फसल (PMKSY)",
    "Up to 90% subsidy for small and marginal farmers on installing drip and sprinkler micro-irrigation systems.": "टपक और फव्वारा सूक्ष्म सिंचाई प्रणाली स्थापित करने पर छोटे और सीमांत किसानों के लिए 90% तक की सब्सिडी।",
    "SMAM Farm Mechanization": "एसएमएएम कृषि यंत्रीकरण",
    "50% to 80% financial assistance for purchasing tractors tillers rotavators power weeders and harvester equipment.": "ट्रैक्टर, टिलर, रोटावेटर, पावर वीडर और हार्वेस्टर उपकरण खरीदने के लिए 50% से 80% वित्तीय सहायता।",
    "Solar Pump (PM-KUSUM Component B)": "सौर पंप (पीएम-कुसुम घटक बी)",
    "Up to 60% combined central and state subsidy for installing standalone solar irrigation pumps (3HP to 10HP).": "स्टैंडअलोन सौर सिंचाई पंप (3HP से 10HP) स्थापित करने के लिए 60% तक संयुक्त केंद्रीय और राज्य सब्सिडी।",
    "Organic Farming (PKVY)": "जैविक खेती (पीकेवीवाई)",
    "Financial assistance of Rs 31000 per hectare for purchasing organic seeds compost bio-pesticides and cluster branding.": "जैविक बीज, खाद, जैव-कीटनाशक और क्लस्टर ब्रांडिंग खरीदने के लिए ₹31000 प्रति हेक्टेयर की वित्तीय सहायता।",
    "Soil Health Card (Free Testing)": "मृदा स्वास्थ्य कार्ड (निःशुल्क परीक्षण)",
    "100% free chemical analysis of soil samples providing customized nutrient dosage cards for 12 essential parameters.": "मिट्टी के नमूनों का 100% निःशुल्क रासायनिक विश्लेषण, जो 12 आवश्यक मानकों के लिए अनुकूलित पोषक तत्व खुराक कार्ड प्रदान करता है।",
    "Subsidized Seed Distribution": "सब्सिडी वाला बीज वितरण",
    "50% subsidy on buying certified high-yield variety (HYV) seeds of wheat paddy pulses and oilseeds from government depots.": "सरकारी डिपो से गेहूं, धान, दलहन और तिलहन के प्रमाणित उच्च उपज वाले (HYV) बीज खरीदने पर 50% सब्सिडी।",
    "Kisan Credit Card (KCC)": "किसान क्रेडिट कार्ड (KCC)",
    "Subsidized credit at 4% interest rate (after subvention) for crop production animal husbandry and fisheries with insurance coverage.": "फसल उत्पादन, पशुपालन और मत्स्य पालन के लिए बीमा कवरेज के साथ 4% ब्याज दर (छूट के बाद) पर रियायती ऋण।",
    "Rythu Bandhu": "रैतु बंधु",
    "Rs 10000 per acre per year as investment support for agriculture and horticulture crops.": "कृषि और बागवानी फसलों के लिए निवेश सहायता के रूप में ₹10000 प्रति एकड़ प्रति वर्ष।",
    "YSR Rythu Bharosa": "वाईएसआर रैतु भरोसा",
    "Financial assistance of Rs 13500 per year for farmer families including tenant farmers in AP.": "आंध्र प्रदेश में पट्टेदार किसानों सहित किसान परिवारों के लिए ₹13500 प्रति वर्ष की वित्तीय सहायता।",
    "National Horticulture Mission": "राष्ट्रीय बागवानी मिशन",
    "50% subsidy for developing orchards cold storages packhouses greenhouses or shade net cultivation.": "फलों के बगीचे, कोल्ड स्टोरेज, पैकहाउस, ग्रीनहाउस या शेड नेट खेती विकसित करने के लिए 50% सब्सिडी।",
    "Custom Hiring Centre Scheme": "कस्टम हायरिंग सेंटर योजना",
    "40% subsidy for farmers or rural youth to set up agricultural machinery rental bank hubs.": "किसानों या ग्रामीण युवाओं के लिए कृषि मशीनरी किराया बैंक हब स्थापित करने के लिए 40% सब्सिडी।",
    "National Beekeeping Mission (NBHM)": "राष्ट्रीय मधुमक्खी पालन मिशन (NBHM)",
    "50% financial assistance for starting apiary units purchasing bee hives colonies and extraction equipment.": "मधुमक्खी पालन इकाइयां शुरू करने, मधुमक्खी के छत्ते, कॉलोनियां और निष्कर्षण उपकरण खरीदने के लिए 50% वित्तीय सहायता।",
    "Fisheries Unit Subsidy (PMMSY)": "मत्स्य पालन इकाई सब्सिडी (PMMSY)",
    "40% to 60% subsidy for constructing aquaculture ponds purchasing fingerlings and establishing fish feed mills.": "मछली पालन तालाबों के निर्माण, उंगली के आकार के बच्चों (फिंगरलिंक्स) को खरीदने और मछली फ़ीड मिलों की स्थापना के लिए 40% से 60% सब्सिडी।",
    "Animal Husbandry Fund (AHIDF)": "पशुपालन कोष (AHIDF)",
    "3% interest subvention on credit loans for setting up dairy processing meat plants or animal feed units.": "डेयरी प्रसंस्करण, मांस संयंत्रों या पशु चारा इकाइयों की स्थापना के लिए क्रेडिट ऋण पर 3% ब्याज छूट।",
    "Krishi Drones Subsidy": "कृषि ड्रोन सब्सिडी",
    "Up to 100% grant for cooperative societies and 40% to 50% subsidy for individual farmers to purchase agricultural spray drones.": "सहकारी समितियों के लिए 100% तक अनुदान और व्यक्तिगत किसानों को कृषि स्प्रे ड्रोन खरीदने के लिए 40% से 50% सब्सिडी।",
    "Agri-Clinic Agri-Business (ACABC)": "कृषि-क्लिनिक कृषि-व्यवसाय (ACABC)",
    "36% to 44% subsidy on start-up loans up to Rs 20 lakh for setting up agricultural consulting or input dealer clinics.": "कृषि परामर्श या इनपुट डीलर क्लीनिक स्थापित करने के लिए ₹20 लाख तक के स्टार्ट-अप ऋण पर 36% से 44% सब्सिडी।",

    // Donate
    supportTitleDonate: "एग्रोमित्रा का समर्थन करें",
    supportDescDonate: "आपका योगदान हमें मिट्टी परीक्षण केंद्रों को बनाए रखने, कृषि एमएल मॉडल को अपडेट करने और छोटे किसानों को स्मार्ट किट वितरित करने में मदद करता है।",
    customAmount: "कस्टम",
    enterAmountPlaceholder: "राशि दर्ज करें (₹)",
    contributeNow: "अभी योगदान करें",
    processing: "प्रसंस्करण...",
    invalidAmount: "कृपया एक मान्य राशि दर्ज करें।",
    failedCreateOrder: "ऑर्डर बनाने में विफल",
    offlineError: "रेजरपे एसडीके लोड होने में विफल रहा। क्या आप ऑफ़लाइन हैं?",
    verifyFailed: "भुगतान मॉक सत्यापन विफल रहा",
    mockSuccess: "सफलता! एग्रोमित्रा का समर्थन करने के लिए धन्यवाद! (लेन-देन का मॉक किया गया)",
    successContribute: "आपके उदार योगदान के लिए धन्यवाद! आपका भुगतान सफल रहा।",
    sigFailed: "हस्ताक्षर सत्यापन विफल रहा",
    errCheckout: "चेकआउट शुरू करने में त्रुटि।",
    ...subsidiesHi
  },
  te: {
    // Navbar & Layout
    home: "హోమ్",
    services: "సేవలు",
    pricing: "మండి ధరలు",
    weather: "వాతావరణం",
    testing: "నేల పరీక్ష",
    schemes: "పథకాలు & సబ్సిడీలు",
    donate: "విరాళం ఇవ్వండి",
    contact: "మమ్మల్ని సంప్రదించండి",
    about: "మా గురించి",
    login: "లాగిన్",
    signup: "సైన్ అప్",
    logout: "లాగౌట్",
    profile: "ప్రొఫైల్ నిర్వహణ",
    theme: "థీమ్ మార్చండి",
    adminPanel: "అడ్మిన్ ప్యానెల్",
    welcome: "అగ్రోమిత్రా కి స్వాగతం",
    recentServices: "ఇటీవల ఉపయోగించిన సేవలు",
    supportTitle: "సహాయం కావాలా?",
    supportDesc: "మా సేవల గురించి మీకు ఏవైనా ప్రశ్నలు లేదా సమస్యలు ఉంటే సహాయం చేయడానికి మా వ్యవసాయ నిపుణులు 24/7 అందుబాటులో ఉన్నారు.",
    callNow: "ఇప్పుడే కాల్ చేయండి",
    emailNow: "ఇప్పుడే ఈమెయిల్ చేయండి",
    location: "స్థలాన్ని ఎంచుకోండి",
    
    // Help Center / FAQ
    faqTitle: "అగ్రోమిత్రా సహాయ కేంద్రం",
    faqSubtitle: "సాధారణ ప్రశ్నలకు సమాధానాలు కనుగొనండి లేదా మా సేవల గురించి మా AI సహాయకుడిని ఏదైనా అడగండి.",
    aiSearchTitle: "అగ్రోమిత్రా AI సహాయకుడిని అడగండి",
    aiSearchPlaceholder: "మీ ప్రశ్నను ఇక్కడ టైప్ చేయండి (ఉదా. 'దీన్ని ఎవరు నిర్మించారు?' లేదా 'నేల పరీక్ష ఎలా పని చేస్తుంది?')...",
    searching: "శోధిస్తోంది...",
    search: "అడగండి",
    matchedQuestion: "సరిపోలిన ప్రశ్న",
    aiResponse: "AI ప్రతిస్పందన",
    generalFaqTitle: "तरचुगा अडिगे प्रश्नलु",
    
    // Contact Us
    contactUsTitle: "మమ్మల్ని సంప్రదించండి / మద్దతు",
    contactUsSubtitle: "ప్రశ్నలు లేదా అభిప్రాయాలు ఉన్నాయా? మమ్మల్ని అడగండి మరియు మా నిపుణులు త్వరగా సమాధానం ఇస్తారు.",
    nameLabel: "పేరు",
    contactNamePlaceholder: "మీ పేరును నమోదు చేయండి",
    emailLabel: "ఈమెయిల్ చిరునామా",
    contactEmailPlaceholder: "మీ ఈమెయిల్ నమోదు చేయండి",
    subjectLabel: "విషయం",
    subjectPlaceholder: "ఇది దేనికి సంబంధించినది?",
    messageLabel: "మీ సందేశం / విచారణ",
    messagePlaceholder: "మీ విచారణను వివరంగా వివరించండి...",
    sending: "సమర్పిస్తోంది...",
    submitQuery: "विचारणनु समर्पिचंडी",
    querySuccess: "మీ సందేశం విజయవంతంగా సమర్పించబడింది! మా బృందం త్వరలో మిమ్మల్ని సంప్రదిస్తుంది.",
    
    // Weather Predictor
    weatherTitle: "వాతావరణ సూచన",
    weatherSubtitle: "రోజువారీ వాతావరణ కొలతలను నమోదు చేయండి లేదా వారం రోజుల పంట సలహాలను పరిశీలించడానికి వీక్లీ అబ్జర్వేటరీని ప్రారంభించండి.",
    sensorAutofill: "సెన్సార్ ఆటోఫిల్",
    weeklyObservatory: "వీక్లీ అబ్జర్వేటరీ",
    precipitationLabel: "వర్షపాతం (మిమీ)",
    maxTempLabel: "గరిష్ట ఉష్ణోగ్రత (°C)",
    minTempLabel: "కనిష్ట ఉష్ణోగ్రత (°C)",
    windLabel: "గాలి వేగం (కిమీ/గం)",
    predictButtonSingle: "ఒక రోజు వాతావరణాన్ని అంచనా వేయండి",
    adviceHeading: "స్మార్ట్ వ్యవసాయ సలహా:",
    predictionHeading: "అంచనా వేసిన పరిస్థితి",
    observatoryTitle: "వీక్లీ వాతావరణ అబ్జర్వేటరీ",
    stationLabel: "గుర్తించిన స్టేషన్",
    forecastLabel: "7 రోజుల సూచన",
    advisoryFor: "కొరకు సలహా",
    
    // Fertilizer Advisor
    soilAdvisorTitle: "ఎరువుల సలహా సాధనం",
    soilAdvisorSubtitle: "సరైన ఎరువుల సూచనలను పొందడానికి నేల NPK మరియు pH విలువలను నమోదు చేయండి.",
    nitrogenLabel: "నైట్రోజన్ (N)",
    phosphorusLabel: "ఫాస్పరస్ (P)",
    potassiumLabel: "పొటాషియం (K)",
    temperatureLabel: "ఉష్ణోగ్రత (°C)",
    humidityLabel: "తేమ (%)",
    moistureLabel: "నేల తేమ (%)",
    soilTypeLabel: "నేల రకం",
    cropTypeLabel: "పంట రకం",
    importSoilReport: "నేల నివేదికను దిగుమతి చేయి",
    generateRecommendation: "సలహాదారు సిఫార్సును రూపొందు",
    calculating: "లెక్కిస్తోంది...",
    soilTestSummary: "నేల పరీక్ష సారాంశం / వ్యాఖ్యలు",
    
    // Mandi Prices
    mandiTitle: "మండి ధరల సూచీ",
    mandiSubtitle: "ప్రభుత్వ డేటాబేస్ నుండి నిజ-సమయ వ్యవసాయ వస్తువుల ధరలు",
    searchState: "రాష్ట్రాన్ని వెతకండి",
    searchCommodity: "పంటను వెతకండి",
    filterDistrict: "జిల్లా / మార్కెట్ ఫిల్టర్",
    refreshBtn: "తాజా ధరలను అప్‌డేట్ చేయి",
    mandiTableCrop: "పంట",
    mandiTableVariety: "రకం",
    mandiTableMarket: "మార్కెట్ / రాష్ట్రం",
    mandiTableMin: "కనిష్ట ధర",
    mandiTableMax: "గరిష్ట ధర",
    mandiTableModal: "సగటు ధర",
    mandiTableDate: "తేదీ",
    
    // Subsidies & Schemes
    subsidiesTitle: "సబ్సిడీలు & పథకాల మ్యాచ్ మేకర్",
    subsidiesSubtitle: "రైతులు మరియు పంట మద్దతు కోసం ప్రభుత్వ పథకాలను కనుగొనండి మరియు సరిపోల్చండి.",
    filterEligibility: "అర్హత ఫిల్టర్",
    matcherFormState: "రాష్ట్రం",
    matcherFormCrop: "ప్రధాన పంట",
    matcherFormLand: "భూమి పరిమాణం (ఎకరాలు)",
    matcherFormIncome: "వార్షిక ఆదాయం (INR)",
    matcherCheckBtn: "నా అర్హతను తనిఖీ చేయి",
    matchedSchemes: "సరిపోలిన పథకాలు",
    aiChatSubtitle: "పథకాల సహాయక చాట్‌బాట్",
    
    // Deals Shop
    shopTitle: "అగ్రోమిత్రా షాప్",
    shopSubtitle: "వ్యవసాయ విత్తనాలు మరియు పరికరాలను కొనుగోలు చేయండి",
    shoppingCart: "షాపింగ్ కార్ట్",
    emptyCart: "మీ కార్ట్ ఖాళీగా ఉంది. కొన్ని ఉత్పత్తులను జోడించండి!",
    totalAmount: "మొత్తం ధర",
    shippingDetails: "షిప్పింగ్ వివరాలు",
    shippingName: "గ్రహీత పేరు",
    shippingAddress: "షిప్పింగ్ చిరునామా",
    shippingPhone: "సంప్రదించాల్సిన నంబర్",
    placeOrder: "ఆర్డర్ చేయి & చెల్లించు",
    addToCart: "కార్ట్‌కు జోడించు",
    
    // About Us
    aboutMission: "మా లక్ష్యం",
    aboutMissionDesc: "వ్యవసాయ రంగాన్ని సుస్థిరం మరియు సంపన్నం చేయడానికి రైతులకు AI ఆధారిత సలహాలు, ప్రత్యక్ష మార్కెట్ ధరలు మరియు స్మార్ట్ వ్యవసాయ సలహాదారుల ద్వారా తోడ్పాటు అందించడం.",
    aboutStory: "మా కథ",
    aboutStoryDesc: "సాంకేతికతను వ్యవసాయ మూలాలకు అనుసంధానించడానికి అగ్రోమిత్రా నిర్మించబడింది. వాతావరణం, నేల ఆరోగ్యం మరియు మార్కెట్ ధరల ప్రత్యక్ష సమాచారాన్ని అందించడం ద్వారా రైతులు సరైన నిర్ణయాలు తీసుకునేలా సహాయపడతాము.",
    aboutDesc: "అగ్రోమిత్రా అనేది స్థానిక భారతీయ రైతులకు అధికారం ఇవ్వడానికి నిర్మించబడిన ఒక అత్యాధునిక వ్యవసాయ సలహా వేదిక. మెషిన్ లెర్నింగ్ ఉపయోగించి, మేము నేల ఎరువులు, పంట ధరల హెచ్చరికలు (మండి), వాతావరణ అంచనా సలహాలు మరియు సరిపోలిన ప్రభుత్వ రాయితీల కోసం నిజ-సమయ సిఫార్సులను అందిస్తాము.",
    aboutTeam: "VIT-AP అభివృద్ధి బృందం",
    aboutTeamDesc: "VIT-AP విశ్వవిద్యాలయంలో క్యాప్‌స్టోన్ చొరవగా అభివృద్ధి చేయబడింది.",
    projectLeads: "ప్రాజెక్ట్ లీడ్స్",
    emailLabelShort: "ఈమెయిల్",
    locationLabelShort: "స్థానం",

    // Footer
    quickLinks: "త్వరిత లింకులు",
    ourOffice: "మా కార్యాలయం",
    connectWithUs: "మమ్మల్ని సంప్రదించండి",
    cultivatingFuture: "సుస్థిర వ్యవసాయ భవిష్యత్తును పెంపొందించడం",
    copyright: "© 2025 అగ్రోమిత్రా. MIT లైసెన్స్ కింద లైసెన్స్ పొందింది.",

    // Login / Signup / Verify
    loginHeader: "లాగిన్",
    signupHeader: "సైన్ అప్",
    emailPlaceholder: "ఈమెయిల్",
    passwordPlaceholder: "పాస్‌వర్డ్",
    loginWithGoogle: "గూగుల్‌తో లాగిన్ అవ్వండి",
    signupWithGoogle: "గూగుల్‌తో సైన్ అప్ అవ్వండి",
    noAccount: "ఖాతా లేదా?",
    alreadyAccount: "ఇప్పటికే ఖాతా ఉందా?",
    namePlaceholder: "పేరు",
    phonePlaceholder: "ఫోన్ నంబర్",
    selectRole: "పాత్రను ఎంచుకోండి",
    roleFarmer: "రైతు",
    roleCustomer: "కస్టమర్",
    requestOtp: "OTPని అభ్యర్థించు",
    sendingOtp: "OTP పంపుతోంది...",
    verifyOtpHeader: "OTPని ధృవీకరించు",
    verifyOtpPrompt: "దయచేసి పంపిన OTPని నమోదు చేయండి",
    enterOtpPlaceholder: "OTPని నమోదు చేయి",
    verifying: "ధృవీకరిస్తోంది...",

    // Dashboard
    adminConsoleSim: "🛠️ అడ్మిన్ కన్సోల్ సిమ్యులేటర్",
    viewMode: "వీక్షణ మోడ్:",
    farmerDashboard: "రైతు డాష్‌బోర్డ్",
    customerDashboard: "కస్టమర్ డాష్‌బోర్డ్",
    backToAdmin: "← అడ్మిన్ కన్సోల్‌కు తిరిగి వెళ్లు",

    // ServiceSection
    loadingActivities: "కార్యకలాపాలను లోడ్ చేస్తోంది...",
    noRecentActivityCustomer: "ఇటీవలి యాక్టివిటీ లేదు. మా వాతావరణ అంచనాలు లేదా డీల్స్ షాప్‌ను చూడటానికి ప్రయత్నించండి!",
    noRecentActivityFarmer: "ఇటీవలి యాక్టివిటీ లేదు. వాతావరణ అంచనాలు లేదా ఎరువుల సలహాలను క్రింద తనిఖీ చేయండి!",
    viewAllServices: "అన్ని సేవలను చూడండి",
    customerCare: "కస్టమర్ కేర్",
    emailSupport: "ఈమెయిల్ మద్దతు",
    serviceHistoryLogs: "సేవా చరిత్ర లాగ్‌లు",
    closeModal: "మూసివేయి",
    noActivitiesFound: "ఎలాంటి యాక్టివిటీలు కనుగొనబడలేదు.",
    openBtn: "ఓపెన్",
    continueBtn: "కొనసాగించు",
    forecastBtn: "సూచన",
    advisoryBtn: "సలహా",
    matcherBtn: "సరిపోల్చండి",
    trackBtn: "ట్రాక్ చేయి",
    viewBtn: "చూడండి",
    weatherPrediction: "వాతావరణ సూచన",
    fertilizerRecommendation: "ఎరువుల సిఫార్సు",
    subsidiesMatcher: "సబ్సిడీల మ్యాచ్ మేకర్",
    soilTestingRequest: "నేల పరీక్ష అభ్యర్థన",
    marketplaceListing: "మార్కెట్‌ప్లేస్ లిస్టింగ్",
    productPurchase: "ఉత్పత్తి కొనుగోలు",

    // RecommendedFeatures
    recommendedFeaturesTitle: "సిఫార్సు చేయబడిన ఫీచర్లు",
    reports: "నివేదికలు",
    reportsDesc: "వివిధ వ్యవసాయ నిర్ధారణలు మరియు సిఫార్సులను యాక్సెస్ చేయండి",
    weatherReportTitle: "వాతావరణ నివేదిక",
    weatherReportDesc: "వాతావరణ అంచనాలు మరియు పంట సలహా చిట్కాలను పొందండి.",
    soilReportTitle: "నేల నివేదిక",
    soilReportDesc: "భౌతిక నేల పరీక్షలను అభ్యర్థించండి మరియు నివేదిక చరిత్రను తనిఖీ చేయండి.",
    priceReportTitle: "ధరల నివేదిక",
    priceReportDesc: "వ్యవసాయ ఉత్పత్తుల ప్రస్తుత మార్కెట్ ధరలు.",
    fertilizerReportTitle: "ఎరువుల నివేదిక",
    fertilizerReportDesc: "నేల NPK ఆధారంగా సరైన ఎరువుల సిఫార్సులు.",
    accessTool: "యాక్సెస్ చేయి",
    cropListingsTitle: "పంట జాబితాలు",
    postMyCrop: "+ నా పంటను పోస్ట్ చేయి",
    cropListingsDesc: "విత్తనాలు లేదా పంటలను నేరుగా ఇతర రైతులకు మరియు వ్యాపారులకు అమ్మండి",
    loadingCropListings: "పంట జాబితాలను లోడ్ చేస్తోంది...",
    listingsCount: "జాబితాలు",
    viewPostings: "పోస్టింగ్‌లను చూడండి",
    postCropModalTitle: "కొత్త పంట / విత్తన జాబితాను పోస్ట్ చేయి",
    selectCrop: "పంటను ఎంచుకోండి",
    cropCategory: "పంట వర్గం",
    vegetables: "కూరగాయలు",
    cereals: "ధాన్యాలు",
    pulses: "పప్పుధాన్యాలు",
    spices: "మసాలా దినుసులు",
    quantityQuintals: "పరిమాణము (క్వింటాళ్లలో)",
    pricePerQuintal: "క్వింటాల్ ధర (₹)",
    yourFullName: "మీ పూర్తి పేరు",
    yourPhoneNumber: "మీ ఫోన్ నంబర్",
    postListing: "జాబితాను పోస్ట్ చేయి",
    posting: "పోస్ట్ చేస్తోంది...",
    close: "మూసివేయి",
    cropPostingsFor: "కొరకు పంట పోస్టింగ్‌లు",
    noPostingsInCategory: "ఈ వర్గంలో ఇంకా పోస్టింగ్‌లు కనుగొనబడలేదు.",
    farmerLabel: "రైతు",
    phoneLabel: "ఫోన్",
    priceLabel: "ధర",
    qtyLabel: "పరిమాణం",

    // Soil Testing
    requestSoilTestTitle: "నేల పరీక్ష కోసం అభ్యర్థించండి",
    requestSoilTestDesc: "మీ పొలం నుండి భౌతిక నేల నమూనా సేకరణ కోసం సమయాన్ని కేటాయించండి. మా నిపుణులు పరీక్షించి మీ నేల ఆరోగ్య నివేదికను అప్‌లోడ్ చేస్తారు.",
    farmLocationAddress: "పొలం చిరునామా",
    farmAddressPlaceholder: "నమూనా సేకరణ కోసం పూర్తి పొలం చిరునామాను నమోదు చేయండి",
    preferredCollectionDate: "సేకరణ తేదీ",
    schedulePickup: "పికప్‌ను షెడ్యూల్ చేయి",
    yourSoilReports: "మీ నేల నివేదికలు & అభ్యర్థనలు",
    noSoilRequests: "ఇంకా నేల పరీక్ష అభ్యర్థనలు షెడ్యూల్ చేయబడలేదు.",
    pickupAddress: "సేకరణ చిరునామా",
    scheduledCollection: "షెడ్యూల్ చేసిన సేకరణ",
    getAdvisorRec: "సలహాదారు సిఫార్సును పొందు",
    statusCompleted: "పూర్తయింది",
    statusAnalyzing: "విశ్లేషిస్తోంది",
    statusCollected: "సేకరించబడింది",
    statusPending: "పెండింగ్",

    // My Orders
    backToShop: "Back to Shop",
    myOrdersTitle: "నా ఆర్డర్‌లు",
    loadingOrders: "మీ ఆర్డర్‌లను లోడ్ చేస్తోంది...",
    noOrdersPlaced: "ఇంకా ఎలాంటి ఆర్డర్‌లు చేయలేదు",
    exploreShopDesc: "అధిక దిగుబడినిచ్చే విత్తనాలు, ఎరువులు మరియు నాణ్యమైన వ్యవసాయ పరికరాలను కొనుగోలు చేయడానికి డీల్స్ షాప్‌ను సందర్శించండి.",
    shopNow: "ఇప్పుడే కొనండి",
    orderPlaced: "ఆర్డర్ చేసిన తేదీ",
    total: "మొత్తం",
    orderId: "ఆర్డర్ ఐడి",
    itemsOrdered: "ఆర్డర్ చేసిన వస్తువులు",
    recipientPhone: "ఫోన్",
    recipientAddress: "చిరునామా",
    noShippingDetails: "షిప్పింగ్ వివరాలు అందించబడలేదు.",
    statusProcessing: "ప్రాసెసింగ్",
    statusShipped: "షిప్పింగ్ చేయబడింది",
    statusDelivered: "డెలివరీ చేయబడింది",
    statusCancelled: "రద్దు చేయబడింది",

    // Subsidies / Chatbot
    allCentral: "అన్నీ / కేంద్ర",
    allCrops: "అన్ని పంటలు",
    categoryAll: "అన్నీ",
    categoryAgri: "వ్యవసాయం",
    categoryFinance: "ఆర్థికం",
    categoryTech: "సాంకేతికత",
    eligible: "అర్హత ఉంది",
    ineligible: "అర్హత లేదు",
    matches: "సరిపోలింది",
    benefitValue: "ప్రయోజనం విలువ",
    noSchemesMatch: "మీ పారామితులకు సరిపోలే పథకాలు లేవు.",
    advisoryBotTitle: "సలహా పథకం బాట్",
    advisoryBotSubtitle: "వ్యవసాయ పథకం సహాయకుడు",
    botWelcome: 'నమస్తే! నేను మీ అగ్రోమిత్రా సబ్సిడీ సహాయకుడిని. ప్రభుత్వ పథకాలు, రుణాలు, పంట భీమా లేదా సోలార్ పంప్ సబ్సిడీల గురించి నన్ను ఏదైనా అడగండి (ఉదా. "పీఎం కిసాన్ కోసం ఎలా నమోదు చేసుకోవాలి?").',
    botError: "క్షమించండి, సలహా సర్వర్ కనెక్ట్ చేయడంలో సమస్య ఏర్పడింది. దయచేసి మళ్లీ ప్రయత్నించండి.",
    botNetworkError: "నెట్‌వర్క్ కనెక్షన్ సమస్య.",
    botPlaceholder: "మీ సబ్సిడీ ప్రశ్నాన్ని ఇక్కడ టైప్ చేయండి...",

    // Dynamic Categories
    "Agriculture": "వ్యవసాయం",
    "Finance": "ఆర్థికం",
    "Technology": "సాంకేతికత",
    "Irrigation": "నీటి పారుదల",

    // Dynamic Scheme Translations
    "PM-Kisan": "పీఎం-కిసాన్",
    "Direct income support of Rs 6000 per year paid in three equal installments of Rs 2000 to all small landholding families.": "చిన్న కమతాల కుటుంబాలన్నింటికీ ఏడాదికి రూ. 6000 పెట్టుబడి సహాయం, మూడు సమాన వాయిదాలలో రూ. 2000 చొప్పున నేరుగా ఖాతాలో జమ చేయబడుతుంది.",
    "PM Fasal Bima Yojana": "పీఎం ఫసల్ బీమా యోజన",
    "Crop insurance with low premium (1.5% to 5%) covering yield loss due to droughts floods pests and localized calamities.": "కరవు, వరదలు, తెగుళ్లు మరియు స్థానిక విపత్తుల వల్ల జరిగే నష్టాన్ని కవర్ చేసే తక్కువ ప్రీమియం (1.5% నుండి 5%) పంట బీమా.",
    "Per Drop More Crop (PMKSY)": "ప్రతి చుక్కకు ఎక్కువ పంట (PMKSY)",
    "Up to 90% subsidy for small and marginal farmers on installing drip and sprinkler micro-irrigation systems.": "డ్రిప్ మరియు స్ప్రింక్లర్ మైక్రో-ఇరిగేషన్ సిస్టమ్స్ ఏర్పాటు చేయడానికి చిన్న మరియు సన్నకారు రైతులకు 90% వరకు రాయితీ.",
    "SMAM Farm Mechanization": "SMAM వ్యవసాయ యంత్రీకరణ",
    "50% to 80% financial assistance for purchasing tractors tillers rotavators power weeders and harvester equipment.": "ట్రాక్టర్లు, టిల్లర్లు, రోటవేటర్లు, పవర్ వీడర్లు మరియు హార్వెస్టర్ పరికరాల కొనుగోలుకు 50% నుండి 80% ఆర్థిక సహాయం.",
    "Solar Pump (PM-KUSUM Component B)": "సౌర పంపు (PM-KUSUM కాంపోనెంట్ B)",
    "Up to 60% combined central and state subsidy for installing standalone solar irrigation pumps (3HP to 10HP).": "స్టాండ్‌అలోన్ సోలార్ ఇరిగేషన్ పంపులను (3HP నుండి 10HP) ఇన్‌స్టాల్ చేయడానికి 60% వరకు ఉమ్మడి కేంద్ర మరియు రాష్ట్ర సబ్సిడీ.",
    "Organic Farming (PKVY)": "సేంద్రీయ వ్యవసాయం (PKVY)",
    "Financial assistance of Rs 31000 per hectare for purchasing organic seeds compost bio-pesticides and cluster branding.": "సేంద్రీయ విత్తనాలు, కంపోస్ట్, బయో-పెస్టిసైడ్స్ మరియు క్లస్టర్ బ్రాండింగ్ కొనుగోలుకు హెక్టారుకు రూ. 31000 ఆర్థిక సహాయం.",
    "Soil Health Card (Free Testing)": "నేల ఆరోగ్య కార్డ్ (ఉచిత పరీక్ష)",
    "100% free chemical analysis of soil samples providing customized nutrient dosage cards for 12 essential parameters.": "12 అవసరమైన పారామితుల కోసం అనుకూలీకరించిన పోషకాల మోతాదు కార్డ్‌లను అందించే నేల నమూనాల 100% ఉచిత రసాయన విశ్లేషణ.",
    "Subsidized Seed Distribution": "సబ్సిడీ విత్తనాల పంపిణీ",
    "50% subsidy on buying certified high-yield variety (HYV) seeds of wheat paddy pulses and oilseeds from government depots.": "ప్రభుత్వ డిపోల నుండి గోధుమలు, వరి, పప్పుధాన్యాలు మరియు నూనెగింజల ధృవీకరించబడిన అధిక దిగుబడి రకం (HYV) విత్తనాలను కొనుగోలు చేయడంపై 50% సబ్సిడీ.",
    "Kisan Credit Card (KCC)": "కిసాన్ క్రెడిట్ కార్డ్ (KCC)",
    "Subsidized credit at 4% interest rate (after subvention) for crop production animal husbandry and fisheries with insurance coverage.": "పంట ఉత్పత్తి, పశుసంవర్ధకం మరియు మత్స్య పరిశ్రమల కోసం బీమా రక్షణతో 4% వడ్డీ రేటుతో సబ్సిడీ రుణం.",
    "Rythu Bandhu": "రైతు బంధు",
    "Rs 10000 per acre per year as investment support for agriculture and horticulture crops.": "వ్యవసాయ మరియు ఉద్యాన పంటల పెట్టుబడి సహాయం కోసం ఎకరాకు ఏడాదికి రూ. 10000.",
    "YSR Rythu Bharosa": "వైఎస్ఆర్ రైతు భరోసా",
    "Financial assistance of Rs 13500 per year for farmer families including tenant farmers in AP.": "ఆంధ్రప్రదేశ్‌లోని కౌలు రైతులతో సహా రైతు కుటుంబాలకు ఏడాదికి రూ. 13500 ఆర్థిక సహాయం.",
    "National Horticulture Mission": "జాతీయ ఉద్యానవన మిషన్",
    "50% subsidy for developing orchards cold storages packhouses greenhouses or shade net cultivation.": "పండ్ల తోటలు, కోల్డ్ స్టోరేజీలు, ప్యాక్‌హౌస్‌లు, గ్రీన్‌హౌస్‌లు లేదా షేడ్ నెట్ సాగును అభివృద్ధి చేయడానికి 50% సబ్సిడీ.",
    "Custom Hiring Centre Scheme": "కస్టమ్ హైరింగ్ సెంటర్ పథకం",
    "40% subsidy for farmers or rural youth to set up agricultural machinery rental bank hubs.": "వ్యవసాయ యంత్రాల అద్దె బ్యాంక్ హబ్‌లను ఏర్పాటు చేయడానికి రైతులు లేదా గ్రామీణ యువతకు 40% సబ్సిడీ.",
    "National Beekeeping Mission (NBHM)": "జాతీయ తేనెటీగల పెంపకం మిషన్ (NBHM)",
    "50% financial assistance for starting apiary units purchasing bee hives colonies and extraction equipment.": "తేనెటీగల పెంపకం యూనిట్లను ప్రారంభించడానికి, తేనెటీగ పెట్టెలు, కాలనీలు మరియు వెలికితీత పరికరాల కొనుగోలుకు 50% ఆర్థిక సహాయం.",
    "Fisheries Unit Subsidy (PMMSY)": "మత్స్య యూనిట్ సబ్సిడీ (PMMSY)",
    "40% to 60% subsidy for constructing aquaculture ponds purchasing fingerlings and establishing fish feed mills.": "ఆక్వాకల్చర్ చెరువుల నిర్మాణం, చేప పిల్లల కొనుగోలు మరియు చేపల మేత మిల్లుల స్థాపనకు 40% నుండి 60% సబ్సిడీ.",
    "Animal Husbandry Fund (AHIDF)": "పశుసంవర్ధక నిధి (AHIDF)",
    "3% interest subvention on credit loans for setting up dairy processing meat plants or animal feed units.": "డైరీ ప్రాసెసింగ్, మాంసం ప్లాంట్లు లేదా పశుగ్రాసం యూనిట్ల ఏర్పాటు కోసం క్రెడిట్ రుణాలపై 3% వడ్డీ రాయితీ.",
    "Krishi Drones Subsidy": "కృషి డ్రోన్స్ సబ్సిడీ",
    "Up to 100% grant for cooperative societies and 40% to 50% subsidy for individual farmers to purchase agricultural spray drones.": "సహకార సంఘాలకు 100% వరకు గ్రాంట్ మరియు వ్యక్తిగత రైతులు వ్యవసాయ స్ప్రే డ్రోన్‌లను కొనుగోలు చేయడానికి 40% నుండి 50% సబ్సిడీ.",
    "Agri-Clinic Agri-Business (ACABC)": "అగ్రి-క్లినిక్ అగ్రి-బిజినెస్ (ACABC)",
    "36% to 44% subsidy on start-up loans up to Rs 20 lakh for setting up agricultural consulting or input dealer clinics.": "వ్యవసాయ కన్సల్టింగ్ లేదా ఇన్‌పుట్ డీలర్ క్లినిక్‌ల ఏర్పాటు కోసం రూ. 20 లక్షల వరకు స్టార్ట్-అప్ రుణాలపై 36% నుండి 44% సబ్సిడీ.",

    // Donate
    supportTitleDonate: "అగ్రోమిత్రాకు మద్దతు ఇవ్వండి",
    supportDescDonate: "మీ విరాళాలు నేల పరీక్షా కేంద్రాలను నిర్వహించడానికి, వ్యవసాయ ML నమూనాలను నవీకరించడానికి మరియు చిన్న రైతులకు స్మార్ట్ కిట్లను పంపిణీ చేయడానికి మాకు సహాయపడతాయి.",
    customAmount: "కస్టమ్",
    enterAmountPlaceholder: "మొత్తాన్ని నమోదు చేయండి (₹)",
    contributeNow: "ఇప్పుడే విరాళం ఇవ్వండి",
    processing: "ప్రాసెసింగ్...",
    invalidAmount: "దయచేసి సరైన మొత్తాన్ని నమోదు చేయండి.",
    failedCreateOrder: "ఆర్డర్ సృష్టించడంలో విఫలమైంది",
    offlineError: "రేజర్‌పే SDK లోడ్ కాలేదు. మీరు ఆఫ్‌లైన్‌లో ఉన్నారా?",
    verifyFailed: "పేమెంట్ మాక్ వెరిఫికేషన్ విఫలమైంది",
    mockSuccess: "విజయం! అగ్రోమిత్రాకు మద్దతు ఇచ్చినందుకు ధన్యవాదాలు! (లావాదేవీ మాక్ చేయబడింది)",
    successContribute: "మీ ఉదారమైన విరాళానికి ధన్యవాదాలు! మీ చెల్లింపు విజయవంతమైంది.",
    sigFailed: "సిగ్నేచర్ వెరిఫికేషన్ విఫలమైంది",
    errCheckout: "చెకౌట్ ప్రారంభించడంలో లోపం.",
    ...subsidiesTe
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const selectLanguage = (lang) => {
    if (translations[lang]) {
      setLanguage(lang);
    }
  };

  const t = (key) => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, selectLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
